spring:
    profiles:
        active: dev
    mvc:
        view:
            prefix: /build/
    datasource:
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
    port: ${PORT:8080}